### ISSUE TITLE
In DynamicCeiling.sol a function calculateHash is defined but not used continuously

### ISSUE THREAD

**Issue by floAr** [status-im/status-network-token#102]
Function calculateHash is defined in l166, yet revealCurve calls keccak256 by itself in l91.
This should be avoided as it is a source of broken and missmathcing behaviour. If for example further implementation decides to change the hash implementation from keccak256 to something else in the function but someone forgets changing the direct calls -> missmathcing behaviour

**Comment by nfnty** [comment]
Good idea, thanks.
