### ISSUE TITLE
(Medium) Conflicting minimum contribution

### ISSUE THREAD

**Issue by dickolsson** [status-im/status-network-token#110]
## The issue

Conflicting information about the minimum contribution. The smart contract source code must be changed to follow either of the below statements.

Your [terms of condition][toc] states:

> 17. Minimum Contribution Amount:​ Contributions of less than 0.001 ETH do not result in theallocation of SNT, nor will they be refunded.

And the [blog post FAQ][faq] states:

> Q: What is the minimum amount of contribution? 0.01 ETH.

[toc]: https://contribute.status.im/status-terms.pdf
[faq]: https://blog.status.im/new-date-contribution-period-begins-tuesday-june-20th-at-2pm-gmt-e00c56c65ead

## Resolution

Decide on the minimum contribution and align it across; the ToC, the FAQ, the actual smart contracts and their automated tests.

## Severity

*Likelihood* of this the issue happening? **Medium**. I would expect a significant number of people wanting to contribute, but don't want to contribute more than the minimum amount.

*Impact* of the issue? **Medium**. The impact of someone following the stated ToC and otherwise doing a valid transaction but that will be rejected based on conflicting terms should be considered Medium I think.

**Comment by dickolsson** [comment]
I thought that conflicting ToC should be considered Medium severity. But perhaps the severity of this could still be considered Low.

**Comment by dickolsson** [comment]
Looks like the blog post has been corrected. Closing this issue, since there's no longer any conflicting information. Cheers!

**Comment by jarradh** [comment]
thank-you very much @dickolsson we'll be in touch
