### ISSUE TITLE
Announce to public that you will not be accepting transfers from multisig wallets _before_ the token launch.

### ISSUE THREAD

**Issue by MicahZoltu** [status-im/status-network-token#128]
As I have expressed in the PR, I think not allowing multi-sig wallets is a bad idea.  However, since you appear to be going forward with it you _SHOULD_ tell the public about this decision in advance of the crowdsale.  If you don't, there are likely to be many participants that end up burning gas in attempts to contribute with a multi-sig wallet as well as an increased support burden on Status.im, Parity, MetaMask, MEW and Mist teams as people go to them seeking assistance with why they can't contribute the crowdsale.

**Comment by GNSPS** [comment]
I'm very much in favor of a public statement about this.

Think it will only contribute to increase trust from your followers and future contributors.

No dia 17/06/2017, às 17:53, Micah Zoltu <notifications@github.com> escreveu:

**Comment by jarradh** [comment]
We absolutely will make this clear, we actually considered this before making the decision. Ssmart contracts used in crowdsales have been historically really low, iirc there was only about 10 in the DAO and 12 in Bancor.

```
0x6bd33d49d48f76abcd96652e5347e398aa3fda96 BancorBuyer
0xdfd1cf8cb14d2fd2436348a7e943a98b7625a971 wallet
0xdf0ff040e85005b86ee93e89a7bfb91565a502e5 wallet
0x0cd80508239516194ba7202f324efb489df5e756 wallet
0xe82062f270dbbd296ec4820845129d874ea35ace TokenPool
0x4e54f218918ec88d4e7780bdb17d7fb4aaa61527 wallet
0x072bc111ca7698d6e1f0d36fa649d7d36f40d654 wallet
0xf169c5bbe8c8460dfb7c17b4c36a90f70b0a56f7 wallet
0xf6b18d5d5876eea9e194dfbc479fa3134de703ec wallet
0x072bc111ca7698d6e1f0d36fa649d7d36f40d654 wallet
0x257c6bcbdf47d9eee3b2d13de4af9d75d3c681d4 ?? Bancor split wallet.
0xb8b096c107c69bb5594aacebff7e4cced4673460
```
