### ISSUE TITLE
`claimTokens` and `ClaimedTokens` duplicated

### ISSUE THREAD

**Issue by nfnty** [status-im/status-network-token#29]
Refactor to reuse code.

Use unmodified `MiniMeToken` contract, if possible.

**Comment by jbaylina** [comment]
It uses the last version of Minime and it's only added the possibility to extract accidental tokens from the minime.  I'm going to add it in the minime standard...

**Comment by nfnty** [comment]
Alright. As long as we try to minimize code duplication, it's fine.
