### ISSUE TITLE
Point block delay if revealed after set block

### ISSUE THREAD

**Issue by nfnty** [status-im/status-network-token#32]
Point block delay equal to difference between revealed point and previous if revealed after set block.

Use actual block number, not set, when calculating next.

Clarify that `revealPoint` should use less gas price than contribution TXs, to have previous TXs cleared before next point.

**Comment by jbaylina** [comment]
https://github.com/status-im/status-network-token/pull/60 Allows to change the blocks of the points dinamically, so this should not be an issue.

**Comment by nfnty** [comment]
That's way too complex for this simple issue. We only need to specify a static number of blocks to wait.
