### ISSUE TITLE
24 hour logic after soft cap

### ISSUE THREAD

**Issue by nfnty** [status-im/status-network-token#33]
Public variable equal to calculated `blocks/24h` set at deploy of `DynamicCeiling`.

Decide on if soft cap is one point? Otherwise add soft cap parameter to `setHiddenPoints`.

Options:

* All points except soft cap within `blocks/24h`, set after `endBlock`, modulo logic.
* All points except soft cap treated as being within `blocks/24h`, set block treated as offset from when soft cap limit is reached.
* Division logic of set blocks when `allRevealed` to fit within `blocks/24h` (deviates from spec).

**Comment by jbaylina** [comment]
Because finalize can only be called by the owner before the endBlock, This 24h will be waranteed by the owner.

**Comment by nfnty** [comment]
Tuning curves with specific parameters will fix this. I'll flesh out the calculation script once the code is nearing completion so that fees can be calculated.
