### ISSUE TITLE
Asymptotic dust guard

### ISSUE THREAD

**Issue by nfnty** [status-im/status-network-token#34]
If `cap` is less than `0.01ETH` do not use asymptotic cap logic, to prevent long tail spam attacks.

**Comment by jbaylina** [comment]
Added in PR #60 too

**Comment by nfnty** [comment]
That implementation is not very good. #59 has implemented it as a way to completely fill the limit, where `collectMinimum` still accepts contributions, but caps it at that so that people still get their worth.
