### ISSUE TITLE
Event underscore parameter

### ISSUE THREAD

**Issue by nfnty** [status-im/status-network-token#35]
Prepend underscores to all event parameter.

**Comment by jbaylina** [comment]
If you use events in Javascript is nice to not have undersocores. And in the event there is no reason to put undersocore.

**Comment by nfnty** [comment]
Sure, but consistency makes everything easier. Many functions have similar parameter names already. But w/e everyone agrees on is the best.

**Comment by nfnty** [comment]
And you're using it in MiniMe, so I can't see why not.

**Comment by jarradh** [comment]
Let's keep it consistent, Javascript developers be damned
