### ISSUE TITLE
Failsafe not applied to buyGuaranteed

### ISSUE THREAD

**Issue by colterj199** [status-im/status-network-token#86]
The way the contract is currently structured, there's no guarantee that the maximum amount of Ether raised will be under `failsafe` (e.g., no guarantee that they won't raise 500,000 ETH). This is because `assert(totalNormalCollected.add(toCollect) <= failSafe);` is only checked on buyNormal, not buyGuaranteed. There is a check within setGuaranteedAddress (`require(_limit <= failSafe);`), but that only check that each guaranteed address can't contribute more than `failsafe`, which isn't what a failsafe is meant to be.

There are two ways to fix this issue IMO. First, move that check to doBuy. This is the only option that truly guarantees a failsafe. This does mean that if a guaranteed buyer contributes too late, their tx won't go through. But then, they can submit with high gas price (since the check isn't in guaranteedBuy) and they can submit during the first ceiling (with only SGT holders being able to contribute to), so there's no reason why a guaranteed buyer can't get their transaction in within the first few blocks of the start of the sale.

A less preferred alternative would be, at a minimum, to keep track of the total amount of guaranteed limit allocated, and check that this doesn't exceed a certain amount. For instance,

`function setGuaranteedAddress(address _th, uint256 _limit) public initialized onlyOwner {
        require(getBlockNumber() < startBlock);
        totalGuaranteedAllocated=totalGuaranteedAllocated.add(_limit);
        require(totalGuaranteedAllocated <= guaranteedFailSafe);
        guaranteedBuyersLimit[_th] = _limit;
        GuaranteedAddress(_th, _limit);
}`

Finally, the alternative is to recognize the current behavior as a feature and not a bug, and then stop advertising the failsafe (e.g., 300K ETH) as the maximum amount raised, which is currently what's being communicated.

**Comment by nfnty** [comment]
All guaranteed addresses limits and buys trigger events. Which is why the `failSafe` isn't used more than just used as input validation. Everyone can check how much guaranteed buyers have bought.

**Comment by colterj199** [comment]
I agree, and I'll be monitoring those events :) but still if the idea of the failsafe is to make sure that worst case scenario, you can't raise more than 300,000 ETH, then this won't work.

**Comment by nfnty** [comment]
The `failSafe` is for worst case scenario failure of the dynamic ceilings.

**Comment by colterj199** [comment]
What's the purpose of a programmatic failsafe if there are edge cases around it? You can't control when guaranteed buys will be broadcasted

**Comment by colterj199** [comment]
I see. So it is expected that you might raise more than 300,000? E.g., last ceiling at 200,000 and guaranteed at 150,000?

**Comment by nfnty** [comment]
I can't speak for the Status team, but I'm sure that they will calculate everything carefully to make all ICO participants satisfied.

**Comment by gapar2** [comment]
I still feel like the failsafe mechanism isn't adequate as it is... Bancor got a huge backlash for exceeding their softcap by 100K+ ETH, it'd be much worst if Status exceeded their failsafe...

**Comment by nfnty** [comment]
Not going to happen. The ceilings are engineered and will be carefully tuned so that it never happens. Bancor's ICO contract had nothing to prevent them collecting 1M ETH, unless they themselves manually revealed the soft cap. You will know before the ICO starts how much the last ceiling's limit is and you'll know what the limits of the guaranteed buyers are. Impossible to collect more than that.

**Comment by colterj199** [comment]
Correct, but the sum of the two could be above failsafe. Also AFAIK, you won't know the last ceiling's limit until they actually reveal it, which might come much later.

**Comment by nfnty** [comment]
All ceilings will be revealed by calling `revealMulti()` before the crowdsale starts to make it as smooth as possible. After that it's up to the buyers to deplete the ceilings.

**Comment by colterj199** [comment]
Interesting, that functionality wasn't there when I went through the codebase 2 days ago... looking forward for a bit a stability on these contracts :)

**Comment by nfnty** [comment]
We're almost done, just finishing up the last bits. Doing calculations and writing tests now.

**Comment by jarradh** [comment]
I wasn't aware of the `failSafe` limit as being advertised as the maximum amount raised? Who's doing that and where? 

please send in a PR for option 1, with the check in `doBuy`

**Comment by jarradh** [comment]
The problem is as soon as failSafe == max amount, whales start planning for that.

**Comment by MicahZoltu** [comment]
I believe the issue is that having a failsafe that doesn't actually enforce anything _implies_ to readers that there is an upper limit when in fact there isn't as far as the contracts go.  It also adds complexity for presumably no gain if the limit can be surpassed.

Also, the failsafe provided investors a way to gauge the target valuation of the project, thus allowing them to make an informed investment decision.  If the failsafe doesn't provide an upper limit then people are buying into a project that has an unknown valuation, which is a risk investment for someone investing on fundamentals (which, lets be honest, is basically no-one in the ICO investor space).

**Comment by colterj199** [comment]
You guys still feel that this issue wasn't a big deal? It seems like we are almost going to hit the failsafe, given the last ceiling + guaranteed buys... I can already see that you'll get a *lot* of complains about the greed the team showed through how they set the ceilings (176K) and guaranteed buys (123K). Can you imagine if on top of that you'd actually have busted the failsafe?

Also, why call it a failsafe when it's actually just your max cap? You really should simply have advertised that you were going to raise 300K ETH. This was extremely deceiving, and I'm greatly disappointed.
